### ISSUE TITLE
socket.error Connection refused 

### ISSUE THREAD

**Issue by mrh666** [armon/statsite#159]
Hi Armon,

I have statsite 0.7.1 installed on heavy loaded instances (Storm supervisors). They processed up to 25K metrics per second. Statsite installed with a puppet module dchristensen-statsite v0.2.6. 
Centos 7 - 3.10.0-229.4.2.el7.x86_64. 
Python 2.7.5

/etc/statsite/config:

```
[statsite]
tcp_port = 8125
udp_port = 8125
bind_address = 0.0.0.0
parse_stdin = 0
log_level = DEBUG
flush_interval = 10
timer_eps = 0.01
set_eps = 0.02
stream_cmd = python '/opt/statsite/current/sinks/graphite.py' 'graphite-relay.domain.com' 2003 'statsite.' 3
pid_file = /var/run/statsite.pid
binary_stream = 0
use_type_prefix = 1
extended_counters = 0
```

And sometime I've got this error:
```
Nov  4 12:05:15 storm statsite: Traceback (most recent call last):
Nov  4 12:05:15 storm statsite: File "/opt/statsite/current/sinks/graphite.py", line 94, in <module>
Nov  4 12:05:15 storm statsite: graphite = GraphiteStore(*sys.argv[1:])
Nov  4 12:05:15 storm statsite: File "/opt/statsite/current/sinks/graphite.py", line 34, in __init__
Nov  4 12:05:15 storm statsite: self.sock = self._create_socket()
Nov  4 12:05:15 storm statsite: File "/opt/statsite/current/sinks/graphite.py", line 73, in _create_socket
Nov  4 12:05:15 storm statsite: sock.connect((self.host, self.port))
Nov  4 12:05:15 storm statsite: File "/usr/lib64/python2.7/socket.py", line 224, in meth
Nov  4 12:05:15 storm statsite: return getattr(self._sock,name)(*args)
Nov  4 12:05:15 storm statsite: socket.error: [Errno 111] Connection refused
```

Any idea how to fix/workaround it?

**Comment by armon** [comment]
@mrh666 It looks like the connection to `graphite-relay.domain.com` on port 2003 is being refused. This isn't a bug so much as the upstream sink is just down.

**Comment by mrh666** [comment]
Got it. Thank you Armon!
